[package]
name = "zeromq"
version = "0.1.0"
authors = ["Alexei Kornienko <alexei.kornienko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1"
parking_lot = "0.11"
rand = "0.7"
bytes = "0.5"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["compat"] }
num-traits = "0.2"
enum-primitive-derive = "0.1"
dashmap = "3.11"
crossbeam = "0.7"
uuid = { version = "0.8", features = ["v4"] }
regex = "1"
lazy_static = "1"
log = "0.4"
futures_codec = "0.4"

[dev-dependencies]
chrono = "0.4"
criterion = "0.3"
pretty_env_logger = "0.4"
zmq = "0.9"

[lib]
bench = false

[[bench]]
name = "pub_sub"
harness = false
bench = false

[[bench]]
name = "req_rep"
harness = false
