name: Main CI
on: [push]

jobs:
  lint:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install libzmq
        run: sudo apt update && sudo apt install libzmq3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Cache cargo dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo/
          key: cache-cargo-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --tests --benches --all-features -- --deny warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Install libzmq
        run: sudo apt update && sudo apt install libzmq3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache cargo dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cargo/
          key: cache-cargo-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
